name: 'Terraform'
on:
  push:
    branches:
    - '*'
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: 'production'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v1
    - name: 'Terraform Init'
      run: terraform init
    - name: Terraform Plan
      run: terraform plan -out=tfplan
      run: terraform apply -auto-approve tfplan
      run: terraform plan -out=tfplan
      run: terraform apply -auto-approve -var 'vm_name=GHA-teeraform-VM' -var 'location=Us East' -var 'vm_size=Standard_DS1_v2' -var 'image=Ubuntu Server 22.04LTS-X64Gen2' -var 'admin_username=terra' -var 'admin_password=terraf0rmVMconfiguRation'
    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
